server:
  port: 8888

logging:
  path: ./logs
  file: ./logs/userManager.log

spring:
  application:
    name: UserManager
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT
    username: root
    password: 123

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*